title: Ryanna Ciara Naithram
description: GIS & Remote Sensing • Data Analysis • Research

# Use Chirpy as a remote theme
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme

# Author info
author:
  name: Ryanna Ciara Naithram
  email: ryrynaithram@gmail.com
  github: ryannanaithram
  linkedin: your-linkedin-url

# Navigation (optional — Chirpy uses sidebar nav by default)
header_pages:
  - index.md
  - projects.md

# Markdown & code highlighting
markdown: kramdown
highlighter: rouge

