title: Ryanna Ciara Naithram
description: GIS & Remote Sensing • Data Analysis • Research

theme: jekyll-theme-primer

# Author info
author:
  name: Ryanna Ciara Naithram
  email: ryrynaithram@gmail.com
  github: ryannanaithram

# Navigation (optional — Chirpy uses sidebar nav by default)
header_pages:
  - index.md
  - projects.md

# Markdown & code highlighting
markdown: kramdown
highlighter: rouge

