remote_theme: "mmistakes/minimal-mistakes"
author:
  name: "Ryanna Naithram"
  avatar: "/assets/images/headshot.jpg"   # optional headshot
  bio: "Atmospheric science • Remote sensing • GIS • Python"
  location: "Beltsville, MD"
