remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
author:
  name: "Ryanna Naithram"
  bio: "Atmospheric science • Remote sensing • GIS • Python"
  location: "Beltsville, MD"
